/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.41
 * Generated at: 2023-04-23 06:48:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.nuxeo.runtime.api.Framework;
import org.nuxeo.ecm.platform.ui.web.auth.plugins.AnonymousAuthenticator;

public final class nuxeo_005ferror_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("file:/Users/issuser/Work/project/amazon/nuxeo-server-tomcat-2021.1/nxserver/lib/jstl-1.2.jar", Long.valueOf(1611015970000L));
    _jspx_dependants.put("jar:file:/Users/issuser/Work/project/amazon/nuxeo-server-tomcat-2021.1/nxserver/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("jar:file:/Users/issuser/Work/project/amazon/nuxeo-server-tomcat-2021.1/nxserver/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153356282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("org.nuxeo.ecm.platform.ui.web.auth.plugins.AnonymousAuthenticator");
    _jspx_imports_classes.add("org.nuxeo.runtime.api.Framework");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

  String context = request.getContextPath();
  String user_message = (String) request.getAttribute("user_message");
  user_message = user_message != null ? user_message : "";
  String exception_message = (String) request.getAttribute("exception_message");
  String stackTrace = (String) request.getAttribute("stackTrace");
  String request_dump = (String) request.getAttribute("request_dump");
  Boolean isDevModeSet = (Boolean) request.getAttribute("isDevModeSet");
  java.util.ResourceBundle bundle = (java.util.ResourceBundle) request.getAttribute("messageBundle");
  boolean isAnonymous = AnonymousAuthenticator.isAnonymousRequest(request);

      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("  <title>");
      out.print( bundle.getString("label.errorPage.title") );
      out.write("</title>\n");
      out.write("  <style type=\"text/css\">\n");
      out.write("<!--\n");
      out.write("body { background: url(\"");
      out.print(context);
      out.write("/img/error_pages/page_background.gif\") repeat scroll 0 0 transparent;\n");
      out.write("  color: #999;\n");
      out.write("  font: normal 100%/1.5 \"Lucida Grande\", Arial, Verdana, sans-serif;\n");
      out.write("  margin: 0;\n");
      out.write("  text-align: center }\n");
      out.write("\n");
      out.write(".container {  margin: 2em auto;\n");
      out.write("  text-align: center;\n");
      out.write("  width: 70% }\n");
      out.write("\n");
      out.write("h1 { color: #000;\n");
      out.write("  font-size: 150%;\n");
      out.write("  margin: 3.5em 0 .5em 0 }\n");
      out.write("\n");
      out.write("h2 { color: #b20000;\n");
      out.write("  font-size: 110%;\n");
      out.write("  margin: 1em }\n");
      out.write("\n");
      out.write("h1, h2 { font-weight: bold }\n");
      out.write("\n");
      out.write("p { max-width: 600px; margin: .4em auto }\n");
      out.write("\n");
      out.write("a.block { background: url(\"");
      out.print(context);
      out.write("/img/error_pages/refresh.png\") no-repeat scroll center 10px #fff;\n");
      out.write("  border: 1px solid #ddd;\n");
      out.write("  border-radius: 5px;\n");
      out.write("  color: #00729c;\n");
      out.write("  display: inline-block;\n");
      out.write("  font-weight: bold;\n");
      out.write("  margin: .4em;\n");
      out.write("  padding: 3em .5em .8em;\n");
      out.write("  text-align: center;\n");
      out.write("  text-decoration: none;\n");
      out.write("  vertical-align: top;\n");
      out.write("  width: 7em }\n");
      out.write("a.block:hover { background-color: #e9f1f4; border-color: #e9f1f4; color: #000 }\n");
      out.write("a.block.back { background-image: url(\"");
      out.print(context);
      out.write("/img/error_pages/back.png\") }\n");
      out.write("a.block.stack { background-image: url(\"");
      out.print(context);
      out.write("/img/error_pages/show.png\") }\n");
      out.write("a.block.dump { background-image: url(\"");
      out.print(context);
      out.write("/img/error_pages/view.png\") }\n");
      out.write("\n");
      out.write(".block img { display: block;\n");
      out.write("    margin: 0 auto }\n");
      out.write("\n");
      out.write(".links { margin: 2em 0 0 0 }\n");
      out.write(".links span { display: inline-block;\n");
      out.write("  font-size: 85% }\n");
      out.write("\n");
      out.write(".errorDetail { background-color:#fff;\n");
      out.write("  border: 1px solid #ccc;\n");
      out.write("  border-radius: 5px;\n");
      out.write("  height: 40%;\n");
      out.write("  margin: 1em auto;\n");
      out.write("  overflow: auto;\n");
      out.write("  padding: 0.5em;\n");
      out.write("  text-align: left;\n");
      out.write("  width: 100% }\n");
      out.write("-->\n");
      out.write("  </style>\n");
      out.write("  <script language=\"javascript\" type=\"text/javascript\">\n");
      out.write("    function toggleError(id) {\n");
      out.write("      var style = document.getElementById(id).style;\n");
      out.write("      if (\"block\" == style.display) {\n");
      out.write("        style.display = \"none\";\n");
      out.write("      } else {\n");
      out.write("        style.display = \"block\";\n");
      out.write("      }\n");
      out.write("    }\n");
      out.write("  </script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("  <div class=\"container\">\n");
      out.write("    <h1>");
      out.print( bundle.getString("label.errorPage.title") );
      out.write("</h1>\n");
      out.write("\n");
      out.write("    ");
 if (!isAnonymous) { 
      out.write("\n");
      out.write("      <p>");
      if (_jspx_meth_c_005fout_005f0(_jspx_page_context))
        return;
      out.write("</p>\n");
      out.write("      <div class=\"links\">\n");
      out.write("\n");
      out.write("        <a class=\"block back\" href=\"");
      out.print(context );
      out.write("/\">\n");
      out.write("          <span>");
      out.print( bundle.getString("label.errorPage.goBack") );
      out.write("</span>\n");
      out.write("        </a>\n");
      out.write("        <a class=\"block change\" href=\"");
      out.print(context);
      out.write("/logout\">\n");
      out.write("          <span>");
      out.print( bundle.getString("label.errorPage.changeUsername") );
      out.write("</span>\n");
      out.write("        </a>\n");
      out.write("\n");
      out.write("        ");
 if (isDevModeSet) { 
      out.write("\n");
      out.write("          <a class=\"block stack\" href=\"#\" onclick=\"javascript:toggleError('stackTrace'); return false;\">\n");
      out.write("            <span>");
      out.print( bundle.getString("label.errorPage.showStackTrace") );
      out.write("</span>\n");
      out.write("          </a>\n");
      out.write("          <a class=\"block dump\"href=\"#\" onclick=\"javascript:toggleError('requestDump'); return false;\">\n");
      out.write("            <span>");
      out.print( bundle.getString("label.errorPage.viewContextDump") );
      out.write("</span>\n");
      out.write("          </a>\n");
      out.write("\n");
      out.write("          <div class=\"errorDetail\" id=\"stackTrace\" style=\"display: none;\">\n");
      out.write("            <h2>");
      if (_jspx_meth_c_005fout_005f1(_jspx_page_context))
        return;
      out.write("</h2>\n");
      out.write("            <inputTextarea rows=\"20\" cols=\"100\" readonly=\"true\">\n");
      out.write("              <pre>\n");
      out.write("                ");
      if (_jspx_meth_c_005fout_005f2(_jspx_page_context))
        return;
      out.write("\n");
      out.write("              </pre>\n");
      out.write("            </inputTextarea>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("          <div class=\"errorDetail\" id=\"requestDump\" style=\"display: none;\">\n");
      out.write("            <h2>");
      out.print( bundle.getString("label.errorPage.context") );
      out.write("</h2>\n");
      out.write("            <inputTextarea rows=\"20\" cols=\"100\" readonly=\"true\">\n");
      out.write("              <pre>\n");
      out.write("                ");
      if (_jspx_meth_c_005fout_005f3(_jspx_page_context))
        return;
      out.write("\n");
      out.write("              </pre>\n");
      out.write("            </inputTextarea>\n");
      out.write("          </div>\n");
      out.write("        ");
} 
      out.write("\n");
      out.write("\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("    ");
} else { 
      out.write("\n");
      out.write("      <p>");
      out.print( bundle.getString("label.errorPage.anonymous.description") );
      out.write("</p>\n");
      out.write("      <div class=\"links\">\n");
      out.write("        <a class=\"block change\" href=\"");
      out.print(context);
      out.write("/logout\">\n");
      out.write("          <span>");
      out.print( bundle.getString("label.errorPage.anonymous.signIn") );
      out.write("</span>\n");
      out.write("        </a>\n");
      out.write("      </div>\n");
      out.write("    ");
} 
      out.write("\n");
      out.write("\n");
      out.write("  </div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f0_reused = false;
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent(null);
      // /nuxeo_error.jsp(98,9) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user_message}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      _jspx_th_c_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f1_reused = false;
    try {
      _jspx_th_c_005fout_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f1.setParent(null);
      // /nuxeo_error.jsp(117,16) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${exception_message}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f1 = _jspx_th_c_005fout_005f1.doStartTag();
      if (_jspx_th_c_005fout_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
      _jspx_th_c_005fout_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f2 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f2_reused = false;
    try {
      _jspx_th_c_005fout_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f2.setParent(null);
      // /nuxeo_error.jsp(120,16) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f2.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${stackTrace}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f2 = _jspx_th_c_005fout_005f2.doStartTag();
      if (_jspx_th_c_005fout_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f2);
      _jspx_th_c_005fout_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f3 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f3_reused = false;
    try {
      _jspx_th_c_005fout_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f3.setParent(null);
      // /nuxeo_error.jsp(129,16) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f3.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${request_dump}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f3 = _jspx_th_c_005fout_005f3.doStartTag();
      if (_jspx_th_c_005fout_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f3);
      _jspx_th_c_005fout_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f3_reused);
    }
    return false;
  }
}
